### ISSUE TITLE
Distances in newick output files

### ISSUE THREAD

**Issue by crarlus** [arvestad/FastPhylo#1]
Hi,
maybe I am missing something, but I don't see the distances in the outout newick file. My call is
```
fnj -I phylip -O newick -o fastphylo_nj.nwk fastphylo_dist.phylib
```

What I get is
```
((Sample0040,Sample9379),(((((((((((((((((Sample0044,Sample00690),Sample00131),Sample00143) ...
```
i.e. no distance values are displayed.

Is there an option I am not aware of?

**Comment by arvestad** [comment]
If you want the distances, you can use option -m NJ or, perhaps better, -m BIONJ. Those are O(n^3) algorithms however, while FNJ (the default) is O(n^2). 

	L
